export interface EscolaConfig {
  nome: string;
  cidade: string;
  uf: string;
  alunos: number;
  nota: number;
  proficiencia: number;
  risco: number;
  percentualRisco: number;
}

export const ESCOLAS: Record<string, EscolaConfig> = {
  brasil_todos: {
    nome: 'Brasil (Todos)',
    cidade: 'Nacional',
    uf: 'BR',
    alunos: 89016,
    nota: 67.01,
    proficiencia: 0.0,
    risco: 0,
    percentualRisco: 0,
  },
  brasil_concluintes: {
    nome: 'Brasil (Concluintes)',
    cidade: 'Nacional',
    uf: 'BR',
    alunos: 39256,
    nota: 65.03,
    proficiencia: -0.11,
    risco: 0,
    percentualRisco: 0,
  },
  enamed_5: {
    nome: 'ENAMED 5 (49 faculdades)',
    cidade: 'Nacional',
    uf: 'BR',
    alunos: 4129,
    nota: 73.42,
    proficiencia: 0.36,
    risco: 0,
    percentualRisco: 0,
  },
  unimar: {
    nome: 'UNIMAR',
    cidade: 'Marília',
    uf: 'SP',
    alunos: 163,
    nota: 60.56,
    proficiencia: -0.37,
    risco: 31,
    percentualRisco: 19,
  },
  unifaa: {
    nome: 'UNIFAA',
    cidade: 'Valença',
    uf: 'RJ',
    alunos: 220,
    nota: 64.71,
    proficiencia: -0.13,
    risco: 23,
    percentualRisco: 10,
  },
  integrado: {
    nome: 'Faculdade Integrado',
    cidade: 'Campo Mourão',
    uf: 'PR',
    alunos: 129,
    nota: 63.39,
    proficiencia: -0.21,
    risco: 58,
    percentualRisco: 45,
  },
  multivix_vitoria: {
    nome: 'Multivix Vitória',
    cidade: 'Vitória',
    uf: 'ES',
    alunos: 137,
    nota: 66.75,
    proficiencia: -0.02,
    risco: 60,
    percentualRisco: 43,
  },
  multivix_cachoeiro: {
    nome: 'Faculdade Brasileira de Cachoeiro',
    cidade: 'Cachoeiro de Itapemirim',
    uf: 'ES',
    alunos: 109,
    nota: 65.28,
    proficiencia: -0.1,
    risco: 53,
    percentualRisco: 48,
  },
  slmandic_araras: {
    nome: 'SLMandic Araras',
    cidade: 'Araras',
    uf: 'SP',
    alunos: 83,
    nota: 56.76,
    proficiencia: -0.58,
    risco: 38,
    percentualRisco: 45,
  },
  slmandic_campinas: {
    nome: 'SLMandic Campinas',
    cidade: 'Campinas',
    uf: 'SP',
    alunos: 191,
    nota: 62.2,
    proficiencia: -0.27,
    risco: 104,
    percentualRisco: 54,
  },
  facene_rn: {
    nome: 'FACENE Mossoró',
    cidade: 'Mossoró',
    uf: 'RN',
    alunos: 126,
    nota: 60.26,
    proficiencia: -0.39,
    risco: 66,
    percentualRisco: 52,
  },
  unifoa: {
    nome: 'UNIFOA',
    cidade: 'Volta Redonda',
    uf: 'RJ',
    alunos: 119,
    nota: 61.71,
    proficiencia: -0.3,
    risco: 47,
    percentualRisco: 39,
  },
  emescam: {
    nome: 'EMESCAM',
    cidade: 'Vitória',
    uf: 'ES',
    alunos: 135,
    nota: 69.97,
    proficiencia: 0.17,
    risco: 60,
    percentualRisco: 44,
  },
  afya_consolidado: {
    nome: 'Afya (Consolidado)',
    cidade: '20 unidades',
    uf: 'BR',
    alunos: 2870,
    nota: 61.92,
    proficiencia: -0.29,
    risco: 5,
    percentualRisco: 0,
  },
  einstein: {
    nome: 'Albert Einstein',
    cidade: 'São Paulo',
    uf: 'SP',
    alunos: 118,
    nota: 71.9,
    proficiencia: 0.28,
    risco: 56,
    percentualRisco: 47,
  },
};

export const LEGENDAS: Record<string, Record<string, string>> = {
  ciclo: {
    M2: 'ENAMED-2 - Ciclo Básico (Final do 2º ano)',
    M4: 'ENAMED-4 - Ciclo Clínico (Final do 4º ano)',
    M6: 'ENAMED-6 - Internato (Final do 6º ano)',
  },
  eixo_cognitivo: {
    E1: 'Conhecimento e Compreensão',
    E2: 'Aplicação e Análise',
    E3: 'Avaliação e Julgamento Ético-Profissional',
  },
  nivel_cognitivo: {
    NC1: 'Conhecimento e Compreensão (Cognitivo)',
    NC2: 'Aplicação e Execução Prática (Psicomotor)',
    NC3: 'Raciocínio Clínico e Julgamento Ético (Atitudinal)',
  },
  eixo_transversal: {
    AT: 'Atenção à Saúde - Cuidado integral centrado na pessoa',
    GS: 'Gestão em Saúde - Planejamento, equipe, políticas',
    ES: 'Educação em Saúde - Aprendizagem contínua, educação permanente',
  },
  competencia: {
    'C-I': 'Singularidade - Respeitar a singularidade de cada pessoa',
    'C-II': 'Hipóteses diagnósticas - Formular hipóteses e plano propedêutico',
    'C-III': 'Exames complementares - Solicitar e interpretar',
    'C-IV': 'Planos terapêuticos - Elaborar, pactuar e acompanhar',
    'C-V': 'Urgências/emergências - Reconhecer e tratar',
    'C-VI': 'Procedimentos básicos - Indicar e realizar procedimentos clínicos e cirúrgicos',
    'C-VII': 'Necessidades coletivas - Identificar necessidades coletivas de saúde',
    'C-VIII': 'Promoção e vigilância - Planejar e implementar ações',
    'C-IX': 'Princípios do SUS - Aplicar princípios e políticas do SUS',
    'C-X': 'Comunicação - Comunicar-se com pacientes, famílias e equipes',
    'C-XI': 'Equipe multiprofissional - Trabalhar em equipe multiprofissional',
    'C-XII': 'Ética e deontologia - Respeitar normas éticas e deontológicas',
    'C-XIII': 'Autorreflexão - Atitude autorreflexiva e aprendizado permanente',
    'C-XIV': 'TICs em saúde - Tecnologias da informação e comunicação',
    'C-XV': 'Emergências sanitárias - Atuar em emergências e desastres',
  },
  dominio: {
    'D-I': 'Bases moleculares e celulares (Bloco I)',
    'D-II': 'Processos fisiológicos do ciclo de vida (Bloco I)',
    'D-III': 'Determinantes sociais, culturais e ecológicos (Bloco I)',
    'D-IV': 'Ética, bioética e segurança de dados (Bloco II)',
    'D-V': 'Direitos humanos e inclusão (Bloco II)',
    'D-VI': 'Semiologia (Bloco II)',
    'D-VII': 'Comunicação em saúde (Bloco II)',
    'D-VIII': 'Registro e documentação médica (Bloco II)',
    'D-IX': 'Propedêutica e diagnóstico (Bloco III)',
    'D-X': 'Terapêutica (Bloco III)',
    'D-XI': 'Prognóstico e prevenção (Bloco III)',
    'D-XII': 'Reabilitação (Bloco III)',
    'D-XIII': 'Promoção e educação em saúde (Bloco III)',
    'D-XIV': 'Políticas de saúde e SUS (Bloco IV)',
    'D-XV': 'Gestão de serviços (Bloco IV)',
    'D-XVI': 'Epidemiologia (Bloco IV)',
    'D-XVII': 'Vigilância em saúde (Bloco IV)',
    'D-XVIII': 'Saúde ambiental e ocupacional (Bloco IV)',
    'D-XIX': 'Liderança e trabalho em equipe (Bloco IV)',
    'D-XX': 'Metodologia científica e MBE (Bloco IV)',
    'D-XXI': 'Tecnologias da informação (Bloco IV)',
  },
  cenario: {
    APS: 'Atenção Primária à Saúde (UBS, ESF, NASF-AB)',
    URG: 'Urgência e Emergência (UPA, SAMU, PS)',
    MAT: 'Rede Materno-Infantil (Maternidades, Casas de parto)',
    RAPS: 'Atenção Psicossocial (CAPS I/II/AD)',
    CRON: 'Doenças Crônicas (Ambulatórios, Atenção domiciliar)',
    REAB: 'Reabilitação (Centros de referência)',
    GESTAO: 'Gestão em Saúde (Planejamento, equipe, políticas)',
  },
  bloom: {
    Lembrar: '1 - Recuperar informação da memória',
    Entender: '2 - Compreender significado, interpretar',
    Aplicar: '3 - Usar conhecimento em situação prática',
    Analisar: '4 - Decompor em partes, identificar relações',
    Avaliar: '5 - Fazer julgamentos baseados em critérios',
    Criar: '6 - Produzir algo novo, sintetizar',
  },
  area_formacao: {
    CLIN: 'Clínica Médica - Diagnóstico e terapêutico em adultos',
    CIR: 'Cirurgia Geral - Manejo cirúrgico básico, trauma e urgências',
    GO: 'Ginecologia e Obstetrícia - Cuidado integral à saúde da mulher',
    PED: 'Pediatria - Cuidado integral de crianças e adolescentes',
    MFC: 'Medicina de Família e Comunidade - Atenção primária, cuidado longitudinal',
    SM: 'Saúde Mental - Reconhecimento, manejo e atenção psicossocial',
    SC: 'Saúde Coletiva - Epidemiologia, vigilância, gestão do SUS, bioética',
  },
};

// Configuração das seções de dimensão do relatório
export interface DimensionConfig {
  titulo: string;
  indiceKey: string;
  sprmedKey?: string; // se null, calcular taxas dinâmicas
  legendaKey?: string;
}

export const DIMENSOES: DimensionConfig[] = [
  { titulo: 'Ciclo Formativo', indiceKey: 'por_ciclo', sprmedKey: 'ciclos', legendaKey: 'ciclo' },
  { titulo: 'Taxonomia de Bloom', indiceKey: 'por_bloom', sprmedKey: 'bloom', legendaKey: 'bloom' },
  { titulo: 'Competências ENAMED', indiceKey: 'por_competencia', sprmedKey: 'competencias', legendaKey: 'competencia' },
  { titulo: 'Domínios de Conteúdo', indiceKey: 'por_dominio', sprmedKey: 'dominios', legendaKey: 'dominio' },
  { titulo: 'Cenários de Atuação', indiceKey: 'por_cenario', sprmedKey: 'cenarios', legendaKey: 'cenario' },
  { titulo: 'Eixo Cognitivo', indiceKey: 'por_eixo_cognitivo', legendaKey: 'eixo_cognitivo' },
  { titulo: 'Nível Cognitivo', indiceKey: 'por_nivel_cognitivo', legendaKey: 'nivel_cognitivo' },
  { titulo: 'Eixos Transversais', indiceKey: 'por_eixo_transversal', legendaKey: 'eixo_transversal' },
  { titulo: 'Área de Formação', indiceKey: 'por_area_formacao', legendaKey: 'area_formacao' },
  { titulo: 'Áreas de Conhecimento', indiceKey: 'por_area' },
  { titulo: 'Subespecialidades e Temas', indiceKey: 'por_subespecialidade' },
];
